spring:
  profiles:
    active: local

---

spring:
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: info

jwt:
  header: Authorization
  secret: dd2901cdc1e1ddec8cd3eb0b55935ea07747371191e52e1e46838b82919a706427ee165e6519aacdb8b943cab27d9487a7a15893f944ba230fec0c3e3d0eba2f
  token-validity-in-seconds: 86400