spring:
  profiles:
    active: local

---
spring:

  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop # TODO : 수정 필요
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: debug

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400